hub:
  config:
    JupyterHub:
      admin_access: true
      admin_users:
        - jovyan
  # extraConfig:
  #   myConfig.py: |
  #     c.JupyterHub.allow_named_servers = True
  #     c.JupyterHub.named_server_limit_per_user = 2
singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: 2343e33dec46
  profileList:
    - display_name: "Minimal environment"
      description: "Python."
      default: true
    - display_name: "Datascience environment"
      description: "Python, R, and Julia."
      kubespawner_override:
        image: jupyter/datascience-notebook
    - display_name: "pySpark"
      description: "Spark binary with Python support."
      kubespawner_override:
        image: jupyter/pyspark-notebook
